### ISSUE TITLE
Why is not recognizing a jQuery

### ISSUE THREAD

**Issue by wellingtonamaralleitao** [velesin/jasmine-jquery#283]
``` javascript
{
  "spec_dir": "spec",
  "spec_files": [
    "**/*[sS]pec.js"
  ],
  "helpers": [
    "helpers/**/jquery.min.js",
    "helpers/**/jasmine.js",
    "helpers/**/jasmine-jquery.js"
  ],
  "stopSpecOnExpectationFailure": false,
  "random": false
}

```

```
$ jasmine
module.js:327
    throw err;
    ^

Error: Cannot find module 'jquery'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/franklinsantos/webmail2016/skins/webmail2016/spec/helpers/jasmine-jquery.js:32:37
    at Object.<anonymous> (/home/franklinsantos/webmail2016/skins/webmail2016/spec/helpers/jasmine-jquery.js:36:2)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

```

**Comment by shadiakiki1986** [comment]
In my setup I don't have a `helpers` section. Check [this](https://gist.github.com/jrhorn424/de8ff5ccea8e53d777f0), and run `npm install jquery --save-dev` on top of that
