### ISSUE TITLE
Chrome XMLHttpRequest cannot load

### ISSUE THREAD

**Issue by stevehorn** [velesin/jasmine-jquery#4]
When trying to use loadFixtures() to load a local html file, Chrome (v7.0.517.41) returns this error:
Origin null is not allowed by Access-Control-Allow-Origin.

Is there a browser setting that I can tweak to get around this error?  Firefox and IE both work fine.

**Comment by NPC** [comment]
Could the same issue happen with Internet Explorer? 

My tests run fine in Firefox, yet in IE11 (v11.0.9600.17728, to be precise) I get the same number of failed tests as in Chrome, while tests that don't attempt to load fixtures work fine.

Here's the error:

Error: Fixture could not be loaded: [filename].html (status: error, message: Access is denied.
)
   at Anonymous function (file:///D:/[path]/JS.Tests/Utils/jasmine-jquery.js:133:11)
   at l (file:///D:/[path]/JQuery/jquery-2.0.0.min.js:4:24576)
   at c.add (file:///D:/[path]/JQuery/jquery-2.0.0.min.js:4:24894)
   at jasmine.Fixtures.prototype.loadFixtureIntoCache_ (file:///D:/[path]/JS.Tests/Utils/jasmine-jquery.js:124:9)
   at jasmine.Fixtures.prototype.getFixtureHtml_ (file:///D:/[path]/JS.Tests/Utils/jasmine-jquery.js:115:7)
   at jasmine.Fixtures.prototype.read (file:///D:/[path]/JS.Tests/Utils/jasmine-jquery.js:77:7)
   at jasmine.Fixtures.prototype.load (file:///D:/[path]/JS.Tests/Utils/jasmine-jquery.js:65:5)
   at jasmine.Fixtures.prototype.proxyCallTo_ (file:///D:/[path]/JS.Tests/Utils/jasmine-jquery.js:161:5)
   at window.loadFixtures (file:///D:/[path]/JS.Tests/Utils/jasmine-jquery.js:782:5)
   at Anonymous function (file:///D:/[path]/JS.Tests/PPM/[my_tests_file].js:44:17)

**Comment by cameronjroe** [comment]
Is there anyway to just use something like https://github.com/karma-runner/karma-html2js-preprocessor and then converting it back into a string.
